- app.js
- config/config.json
- models/index.js
- package-lock.json
- package.json
- routes/index.js
> feat: install third-party packages

- config/config.json
- migrations/20230725073458-create-user.js
- migrations/20230725080701-create-followship.js
- migrations/20230725081631-create-reports.js
- migrations/20230725082709-create-post.js
- migrations/20230725083924-add-postId-to-Report.js
- migrations/20230725090102-create-like.js
- migrations/20230725090405-create-notifications.js
- models/followship.js
- models/like.js
- models/notifications.js
- models/post.js
- models/reports.js
- models/user.js
建立 user, followship, post, like, report, notification model
牽涉到trail的models（ trail, condition, favorite model）則移到下次完成
> feat: add user,follow,post,like,report,notif model

- controllers/apis/admin-controller.js
- controllers/apis/followship-controller.js
- controllers/apis/post-controller.js
- controllers/apis/trail-controller.js
- controllers/apis/user-controller.js
- routes/apis/index.js
- routes/apis/modules/admin.js
- routes/apis/modules/followships.js
- routes/apis/modules/posts.js
- routes/apis/modules/trails.js
- routes/apis/modules/users.js
- routes/index.js
- services/admin-services.js
- services/followship-services.js
- services/post-services.js
- services/trail-services.js
- services/user-services.js
新增 controller/modules/services 結構
> feat: build controller/modules/services

- config/passport.js
- controllers/apis/user-controller.js
- middleware/auth.js
- routes/apis/index.js
- services/user-services.js
> feat: add signIn

- services/user-services.js
> feat: add isSuspended check

- controllers/apis/user-controller.js
- routes/apis/modules/users.js
- services/user-services.js
> feat: add getUserFavoritePost

- controllers/apis/post-controller.js
- routes/apis/index.js
- routes/apis/modules/posts.js
- services/post-services.js
新增 getPosts(取得所有已部屬的post)
新增 getAllPosts(取得所有包含未部屬的post)
> feat: add getPosts and getAllPosts

- controllers/apis/post-controller.js
- routes/apis/index.js
- routes/apis/modules/posts.js
- services/post-services.js
> feat: add getPost

- services/user-services.js
> feat: fix signup

- app.js
- package-lock.json
> feat: config cors

- controllers/apis/user-controller.js
- routes/apis/modules/users.js
- services/user-services.js
> feat: add isReadNotification

- routes/apis/modules/trails.js
- services/trail-services.js
> feat: add getAllTrails & apply optionalAuthenticated

- controllers/apis/trail-controller.js
- routes/apis/modules/trails.js
- services/trail-services.js
> feat: add getTrail

- controllers/apis/post-controller.js
- routes/apis/modules/posts.js
- services/post-services.js
移除 getAllPosts
新增 getUserAllPosts
> feat: remove getAllPosts, add getUserAllPosts

- services/admin-services.js
> feat: add isSuspended

- services/user-services.js
新增 getUserPost 回傳 description
修改 getUserPost 加上限制只能取得以發布的 post
> feat: limit description

- controllers/apis/user-controller.js
- routes/apis/modules/users.js
- services/user-services.js
@jiasyuanchu 
新增 getFavoriteTrail
> feat: add getFavoreiteTrail

- services/admin-services.js
> feat: add role at res

- seeders/20230726080134-user-seeds.js
> fix: fix intro maxLength in user seeds

- services/user-services.js
修改 mySQL查詢中的字母大小寫
這個之前就有改過了不知道為甚麼又出現，可能寫程式的時候沒有隨時fetch最新的origin/main，導致把修改前的程式碼又推上來
> fix: change letter case

- services/post-services.js
> fix: modify search method

- services/post-services.js
修改 searchPostByKeyword 加上 favoriteCount, likeCount, isFavorite, isLike, user Data
> fix: add user data, favoriteCount, likeCount, isFavorite, isLike

- services/post-services.js
> fix: add inProgress at editPost

- config/config.json
> change config production host (private to public)

- services/post-services.js
> feat: add description at getUserAllPost

- migrations/20230728083153-change-track-data-type.js
修正 migrations 20230728083153-change-track-data-type.js down部分應該是移除欄位
> fix: change changeColumn to removeColumn

- services/user-services.js
fb環境變數已新增
需要一個變動去觸發google cloud重新部署
thx
> remove console.log

- services/user-services.js
修改getUserData中的favoritePostCount計算方法
測試「原本被他人收藏的本人post刪除後, 本人的favoritePostCount-1」成功
> fix: revise favoritePostCount in getUserData

- services/user-services.js
> feat: add beFavoritePostCount

- services/trail-services.js
已把kelly帳號的cloud run & SQL建立好
微調程式碼（刪除註解）以觸發部署條件
> fine-tuning
